apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2oai-dai-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: h2oai-dai-operator
  template:
    metadata:
      labels:
        name: h2oai-dai-operator
    spec:
      serviceAccountName: h2oai-dai-operator
      containers:
        - name: h2oai-dai-operator
          # Replace this with the built image name
          image: quay.io/pdmack/h2oai-driverlessai-operator
          command:
          - h2oai-dai-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "h2oai-dai-operator"
