apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: h2oai-dai-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/h2oai-dai-volume
    type: ""
