apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
      app: h2oai-dai-operator
  name: h2oai-dai-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
